<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE kanjidic2 [
	<!-- Version 1.6 - April 2008
	This is the DTD of the XML-format kanji file combining information from
	the KANJIDIC and KANJD212 files. It is intended to be largely self-
	documenting, with each field being accompanied by an explanatory

	The file covers the following kanji:
	(a) the 6,355 kanji from JIS X 0208;
	(b) the 5,801 kanji from JIS X 0212;
	(c) the 3,693 kanji from JIS X 0213 as follows:
		(i) the 2,741 kanji which are also in JIS X 0212 have
		JIS X 0213 code-points (kuten) added to the existing entry;

	At the end of the explanation for a number of fields there is a tag
	with the format (N). This indicates the leading letter(s) of the

	The KANJIDIC documentation should also be read for additional 
	information about the information in the file.
	-->
<!ELEMENT kanjidic2 (header,character*)>
<!ELEMENT header (file_version,database_version,date_of_creation)>
<!--
	The single header element will contain identification information
	about the version of the file 
	-->
<!ELEMENT file_version (#PCDATA)>
<!--
	This field denotes the version of kanjidic2 structure, as more
	than one version may exist.
	-->
<!ELEMENT database_version (#PCDATA)>
<!--
	The version of the file, in the format YYYY-NN, where NN will be
	a number starting with 01 for the first version released in a
	calendar year, then increasing for each version in that year.
	-->
<!ELEMENT date_of_creation (#PCDATA)>
<!--
	The date the file was created in international format (YYYY-MM-DD).
	-->
<!ELEMENT character (literal,codepoint, radical, misc, dic_number?, query_code?, reading_meaning?)*>
<!ELEMENT literal (#PCDATA)>
<!--
	The character itself in UTF8 coding.
	-->
<!ELEMENT codepoint (cp_value+)>
	<!-- 
	The codepoint element states the code of the character in the various
	character set standards.
	-->
<!ELEMENT cp_value (#PCDATA)>
	<!-- 
	The cp_value contains the codepoint of the character in a particular
	standard. The standard will be identified in the cp_type attribute.
	-->
<!ATTLIST cp_value cp_type CDATA #REQUIRED>
	<!-- 
	The cp_type attribute states the coding standard applying to the
	element. The values assigned so far are:
		jis208 - JIS X 0208-1997 - kuten coding (nn-nn)
		jis212 - JIS X 0212-1990 - kuten coding (nn-nn)
		jis213 - JIS X 0213-2000 - kuten coding (p-nn-nn)
		ucs - Unicode 4.0 - hex coding (4 or 5 hexadecimal digits)
	-->
<!ELEMENT radical (rad_value+)>
<!ELEMENT rad_value (#PCDATA)>
	<!-- 
	The radical number, in the range 1 to 214. The particular
	classification type is stated in the rad_type attribute.
	-->
<!ATTLIST rad_value rad_type CDATA #REQUIRED>
	<!-- 
	The rad_type attribute states the type of radical classification.
		classical - based on the system first used in the KangXi Zidian.
		The Shibano "JIS Kanwa Jiten" is used as the reference source.
		nelson_c - as used in the Nelson "Modern Japanese-English 
		Character Dictionary" (i.e. the Classic, not the New Nelson).
		This will only be used where Nelson reclassified the kanji.
	-->
<!ELEMENT misc (grade?, stroke_count+, variant*, freq?, rad_name*,jlpt?)>
<!ELEMENT grade (#PCDATA)>
	<!-- 
	The kanji grade level. 1 through 6 indicates a Kyouiku kanji
	and the grade in which the kanji is taught in Japanese schools. 
	8 indicates it is one of the remaining Jouyou Kanji to be learned 
	in junior high school. 9 indicates it is a Jinmeiyou (for use 
	in names) kanji which in addition  to the Jouyou kanji are approved 
	for use in family name registers and other official documents. 10
	also indicates a Jinmeiyou kanji which is a variant of a
	Jouyou kanji. (G)
	-->
<!ELEMENT stroke_count (#PCDATA)>
	<!-- 
	The stroke count of the kanji, including the radical. If more than 
	one, the first is considered the accepted count, while subsequent ones 
	are common miscounts. (See Appendix E. of the KANJIDIC documentation
	for some of the rules applied when counting strokes in some of the 
	radicals.) (S)
	-->
<!ELEMENT variant (#PCDATA)>
	<!-- 
	Either a cross-reference code to another kanji, usually regarded as a 
	variant, or an alternative indexing code for the current kanji.
	The type of variant is given in the var_type attribute.
	-->
<!ATTLIST variant var_type CDATA #REQUIRED>
	<!-- 
	The var_type attribute indicates the type of variant code. The current
	values are: 
		jis208 - in JIS X 0208 - kuten coding
		jis212 - in JIS X 0212 - kuten coding
		jis213 - in JIS X 0213 - kuten coding
		  (most of the above relate to "shinjitai/kyuujitai" 
		  alternative character glyphs)
		deroo - De Roo number - numeric
		njecd - Halpern NJECD index number - numeric
		s_h - The Kanji Dictionary (Spahn  Hadamitzky) - descriptor
		nelson_c - "Classic" Nelson - numeric
		oneill - Japanese Names (O'Neill) - numeric
		ucs - Unicode codepoint- hex
	-->
<!ELEMENT freq (#PCDATA)>
	<!-- 
	A frequency-of-use ranking. The 2,500 most-used characters have a 
	ranking; those characters that lack this field are not ranked. The 
	frequency is a number from 1 to 2,500 that expresses the relative 
	frequency of occurrence of a character in modern Japanese. This is
	based on a survey in newspapers, so it is biassed towards kanji
	used in newspaper articles. The discrimination between the less
	frequently used kanji is not strong. (Actually there are 2,501
	kanji ranked as there was a tie.)
	-->
<!ELEMENT rad_name (#PCDATA)>
	<!-- 
	When the kanji is itself a radical and has a name, this element
	contains the name (in hiragana.) (T2)
	-->
<!ELEMENT jlpt (#PCDATA)>
	<!--
	The (former) Japanese Language Proficiency test level for this kanji. 
	Values range from 1 (most advanced) to 4 (most elementary). This field 
	does not appear for kanji that were not required for any JLPT level.
	Note that the JLPT test levels changed in 2010, with a new 5-level
	system (N1 to N5) being introduced. No official kanji lists are
	available for the new levels. The new levels are regarded as
	being similar to the old levels except that the old level 2 is
	now divided between N2 and N3.
	-->
<!ELEMENT dic_number (dic_ref+)>
	<!-- 
	This element contains the index numbers and similar unstructured
	information such as page numbers in a number of published dictionaries,
	and instructional books on kanji.
	-->
<!ELEMENT dic_ref (#PCDATA)>
	<!-- 
	Each dic_ref contains an index number. The particular dictionary,
	etc. is defined by the dr_type attribute.
	-->
<!ATTLIST dic_ref dr_type CDATA #REQUIRED>
	<!-- 
	The dr_type defines the dictionary or reference book, etc. to which
	dic_ref element applies. The initial allocation is:
	  nelson_c - "Modern Reader's Japanese-English Character Dictionary",  
	  	edited by Andrew Nelson (now published as the "Classic" 
	  	Nelson).
	  nelson_n - "The New Nelson Japanese-English Character Dictionary", 
	  	edited by John Haig.
	  halpern_njecd - "New Japanese-English Character Dictionary", 
	  	edited by Jack Halpern.
	  halpern_kkd - "Kodansha Kanji Dictionary", (2nd Ed. of the NJECD)
	  	edited by Jack Halpern.
	  halpern_kkld - "Kanji Learners Dictionary" (Kodansha) edited by 
	  	Jack Halpern.
	  halpern_kkld_2ed - "Kanji Learners Dictionary" (Kodansha), 2nd edition
	    (2013) edited by Jack Halpern.
	  heisig - "Remembering The  Kanji"  by  James Heisig.
	  heisig6 - "Remembering The  Kanji, Sixth Ed."  by  James Heisig.
	  gakken - "A  New Dictionary of Kanji Usage" (Gakken)
	  oneill_names - "Japanese Names", by P.G. O'Neill. 
	  oneill_kk - "Essential Kanji" by P.G. O'Neill.
	  moro - "Daikanwajiten" compiled by Morohashi. For some kanji two
	  	additional attributes are used: m_vol:  the volume of the
	  	dictionary in which the kanji is found, and m_page: the page
	  	number in the volume.
	  henshall - "A Guide To Remembering Japanese Characters" by
	  	Kenneth G.  Henshall.
	  sh_kk - "Kanji and Kana" by Spahn and Hadamitzky.
	  sh_kk2 - "Kanji and Kana" by Spahn and Hadamitzky (2011 edition).
	  sakade - "A Guide To Reading and Writing Japanese" edited by
	  	Florence Sakade.
	  jf_cards - Japanese Kanji Flashcards, by Max Hodges and
		Tomoko Okazaki. (Series 1)
	  henshall3 - "A Guide To Reading and Writing Japanese" 3rd
		edition, edited by Henshall, Seeley and De Groot.
	  tutt_cards - Tuttle Kanji Cards, compiled by Alexander Kask.
	  crowley - "The Kanji Way to Japanese Language Power" by
	  	Dale Crowley.
	  kanji_in_context - "Kanji in Context" by Nishiguchi and Kono.
	  busy_people - "Japanese For Busy People" vols I-III, published
		by the AJLT. The codes are the volume.chapter.
	  kodansha_compact - the "Kodansha Compact Kanji Guide".
	  maniette - codes from Yves Maniette's "Les Kanjis dans la tete" French adaptation of Heisig.
	-->
<!ATTLIST dic_ref m_vol CDATA #IMPLIED>
	<!-- 
	See above under "moro".
	-->
<!ATTLIST dic_ref m_page CDATA #IMPLIED>
	<!-- 
	See above under "moro".
	-->
<!ELEMENT query_code (q_code+)>
	<!-- 
	These codes contain information relating to the glyph, and can be used
	for finding a required kanji. The type of code is defined by the
	qc_type attribute.
	-->
<!ELEMENT q_code (#PCDATA)>
	<!--
	The q_code contains the actual query-code value, according to the
	qc_type attribute.
	-->
<!ATTLIST q_code qc_type CDATA #REQUIRED>
	<!-- 
	The qc_type attribute defines the type of query code. The current values
	are:
	  skip -  Halpern's SKIP (System  of  Kanji  Indexing  by  Patterns) 
	  	code. The  format is n-nn-nn.  See the KANJIDIC  documentation 
	  	for  a description of the code and restrictions on  the 
	  	commercial  use  of this data. (P)  There are also
		a number of misclassification codes, indicated by the
		"skip_misclass" attribute.
	  sh_desc - the descriptor codes for The Kanji Dictionary (Tuttle 
	  	1996) by Spahn and Hadamitzky. They are in the form nxnn.n,  
	  	e.g.  3k11.2, where the  kanji has 3 strokes in the 
	  	identifying radical, it is radical "k" in the SH 
	  	classification system, there are 11 other strokes, and it is 
	  	the 2nd kanji in the 3k11 sequence. (I am very grateful to 
	  	Mark Spahn for providing the list of these descriptor codes 
	  	for the kanji in this file.) (I)
	  four_corner - the "Four Corner" code for the kanji. This is a code 
	  	invented by Wang Chen in 1928. See the KANJIDIC documentation 

	  deroo - the codes developed by the late Father Joseph De Roo, and 
	  	published in  his book "2001 Kanji" (Bonjinsha). Fr De Roo 
	  	gave his permission for these codes to be included. (DR)
	  misclass - a possible misclassification of the kanji according
		to one of the code types. (See the "Z" codes in the KANJIDIC
		documentation for more details.)
	  
	-->
<!ATTLIST q_code skip_misclass CDATA #IMPLIED>
	<!--
	The values of this attribute indicate the type if
	misclassification:
	- posn - a mistake in the division of the kanji
	- stroke_count - a mistake in the number of strokes
	- stroke_and_posn - mistakes in both division and strokes
	- stroke_diff - ambiguous stroke counts depending on glyph

<!ELEMENT reading_meaning (rmgroup*, nanori*)>
	<!-- 
	The readings for the kanji in several languages, and the meanings, also
	in several languages. The readings and meanings are grouped to enable
	the handling of the situation where the meaning is differentiated by 
	reading. (T1)
	-->
<!ELEMENT rmgroup (reading*, meaning*)>
<!ELEMENT reading (#PCDATA)>
	<!-- 
	The reading element contains the reading or pronunciation
	of the kanji.
	-->
<!ATTLIST reading r_type CDATA #REQUIRED>
	<!-- 
	The r_type attribute defines the type of reading in the reading
	element. The current values are:
	  pinyin - the modern PinYin romanization of the Chinese reading 
	  	of the kanji. The tones are represented by a concluding 
	  	digit. (Y)
	  korean_r - the romanized form of the Korean reading(s) of the 
	  	kanji.  The readings are in the (Republic of Korea) Ministry 
	  	of Education style of romanization. (W)
	  korean_h - the Korean reading(s) of the kanji in hangul.
	  vietnam - the Vietnamese readings supplied by Minh Chau Pham.
	  ja_on - the "on" Japanese reading of the kanji, in katakana. 
	  	Another attribute r_status, if present, will indicate with
	  	a value of "jy" whether the reading is approved for a
	  	"Jouyou kanji". (The r_status attribute is not currently used.)
		A further attribute on_type, if present,  will indicate with 
		a value of kan, go, tou or kan'you the type of on-reading.
		(The on_type attribute is not currently used.)
	  ja_kun - the "kun" Japanese reading of the kanji, usually in 
		hiragana. 
	  	Where relevant the okurigana is also included separated by a 
	  	".". Readings associated with prefixes and suffixes are 
	  	marked with a "-". A second attribute r_status, if present, 
	  	will indicate with a value of "jy" whether the reading is 
	  	approved for a "Jouyou kanji". (The r_status attribute is 
		not currently used.)
	-->
<!ATTLIST reading on_type CDATA #IMPLIED>
	<!-- 
	See under ja_on above.
	-->
<!ATTLIST reading r_status CDATA #IMPLIED>
	<!-- 
	See under ja_on and ja_kun above.
	-->
<!ELEMENT meaning (#PCDATA)>
	<!-- 
	The meaning associated with the kanji.


	will be coded using the two-letter language code from the ISO 639-1 
	standard. When absent, the value "en" (i.e. English) is implied. ({})
	-->
<!ELEMENT nanori (#PCDATA)>
	<!-- 
	Japanese readings that are now only associated with names.
	-->
]>
<kanjidic2>
<header>
<!-- KANJIDIC 2 - XML format kanji database combining the KANJIDIC
	and KANJD212 files plus the kanji from JIS X 0213.
-->
<file_version>4</file_version>
<database_version>2025-133</database_version>
<date_of_creation>2025-05-13</date_of_creation>
</header>
<!-- Entry for Kanji: 亜 -->
<character>
<literal>亜</literal>

<stroke_count>7</stroke_count>
<freq>1509</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">ア</reading>
<reading r_type="ja_kun">つ.ぐ</reading>
<meaning>Asia</meaning>
<meaning>rank next</meaning>
<meaning>come after</meaning>
<meaning>-ous</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 唖 -->
<character>
<literal>唖</literal>

<stroke_count>10</stroke_count>

<reading_meaning>

<reading r_type="ja_on">ア</reading>
<reading r_type="ja_on">アク</reading>
<reading r_type="ja_kun">おし</reading>
<meaning>mute</meaning>
<meaning>dumb</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 娃 -->
<character>
<literal>娃</literal>

<stroke_count>9</stroke_count>

<reading_meaning>

<reading r_type="ja_on">ア</reading>
<reading r_type="ja_on">アイ</reading>
<reading r_type="ja_on">ワ</reading>
<reading r_type="ja_kun">うつく.しい</reading>
<meaning>beautiful</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 阿 -->
<character>
<literal>阿</literal>

<stroke_count>8</stroke_count>
<freq>1126</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">ア</reading>
<reading r_type="ja_on">オ</reading>
<reading r_type="ja_kun">おもね.る</reading>
<reading r_type="ja_kun">くま</reading>
<meaning>Africa</meaning>
<meaning>flatter</meaning>
<meaning>fawn upon</meaning>
<meaning>corner</meaning>
<meaning>nook</meaning>
<meaning>recess</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 哀 -->
<character>
<literal>哀</literal>

<stroke_count>9</stroke_count>
<freq>1715</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">アイ</reading>
<reading r_type="ja_kun">あわ.れ</reading>
<reading r_type="ja_kun">あわ.れむ</reading>
<reading r_type="ja_kun">かな.しい</reading>
<meaning>pathetic</meaning>
<meaning>grief</meaning>
<meaning>sorrow</meaning>
<meaning>pathos</meaning>
<meaning>pity</meaning>
<meaning>sympathize</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 愛 -->
<character>
<literal>愛</literal>

<stroke_count>13</stroke_count>
<freq>640</freq>
<jlpt>2</jlpt>

<reading_meaning>

<reading r_type="ja_on">アイ</reading>
<reading r_type="ja_kun">いと.しい</reading>
<reading r_type="ja_kun">かな.しい</reading>
<reading r_type="ja_kun">め.でる</reading>
<reading r_type="ja_kun">お.しむ</reading>
<reading r_type="ja_kun">まな</reading>
<meaning>love</meaning>
<meaning>affection</meaning>
<meaning>favourite</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 挨 -->
<character>
<literal>挨</literal>

<stroke_count>10</stroke_count>
<freq>2258</freq>

<reading_meaning>

<reading r_type="ja_on">アイ</reading>
<reading r_type="ja_kun">ひら.く</reading>
<meaning>approach</meaning>
<meaning>draw near</meaning>
<meaning>push open</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 姶 -->
<character>
<literal>姶</literal>

<stroke_count>9</stroke_count>

<reading_meaning>

<reading r_type="ja_on">オウ</reading>
<reading r_type="ja_on">アイ</reading>
<reading r_type="ja_kun">あい</reading>
<meaning>good-looking</meaning>
<meaning>quiet</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 逢 -->
<character>
<literal>逢</literal>

<stroke_count>10</stroke_count>
<stroke_count>9</stroke_count>
<stroke_count>11</stroke_count>
<freq>2116</freq>

<reading_meaning>

<reading r_type="ja_on">ホウ</reading>
<reading r_type="ja_kun">あ.う</reading>
<reading r_type="ja_kun">むか.える</reading>
<meaning>meeting</meaning>
<meaning>tryst</meaning>
<meaning>date</meaning>
<meaning>rendezvous</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 葵 -->
<character>
<literal>葵</literal>

<stroke_count>12</stroke_count>
<freq>2122</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">キ</reading>
<reading r_type="ja_kun">あおい</reading>
<meaning>hollyhock</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 茜 -->
<character>
<literal>茜</literal>

<stroke_count>9</stroke_count>
<freq>2422</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">セン</reading>
<reading r_type="ja_kun">あかね</reading>
<meaning>madder</meaning>
<meaning>red dye</meaning>
<meaning>Turkey red</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 穐 -->
<character>
<literal>穐</literal>

<stroke_count>16</stroke_count>

<reading_meaning>

<reading r_type="ja_on">シュウ</reading>
<reading r_type="ja_kun">あき</reading>
<reading r_type="ja_kun">とき</reading>
<meaning>autumn</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 悪 -->
<character>
<literal>悪</literal>

<stroke_count>11</stroke_count>
<freq>530</freq>
<jlpt>3</jlpt>

<reading_meaning>

<reading r_type="ja_on">アク</reading>
<reading r_type="ja_on">オ</reading>
<reading r_type="ja_kun">わる.い</reading>
<reading r_type="ja_kun">わる-</reading>
<reading r_type="ja_kun">あ.し</reading>
<reading r_type="ja_kun">にく.い</reading>
<reading r_type="ja_kun">-にく.い</reading>
<reading r_type="ja_kun">ああ</reading>
<reading r_type="ja_kun">いずくに</reading>
<reading r_type="ja_kun">いずくんぞ</reading>
<reading r_type="ja_kun">にく.む</reading>
<meaning>bad</meaning>
<meaning>vice</meaning>
<meaning>rascal</meaning>
<meaning>false</meaning>
<meaning>evil</meaning>
<meaning>wrong</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 握 -->
<character>
<literal>握</literal>

<stroke_count>12</stroke_count>
<freq>1003</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">アク</reading>
<reading r_type="ja_kun">にぎ.る</reading>
<meaning>grip</meaning>
<meaning>hold</meaning>
<meaning>mould sushi</meaning>
<meaning>bribe</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 渥 -->
<character>
<literal>渥</literal>

<stroke_count>12</stroke_count>
<freq>2257</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">アク</reading>
<reading r_type="ja_kun">あつ.い</reading>
<reading r_type="ja_kun">うるお.う</reading>
<meaning>kindness</meaning>
<meaning>moisten</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 旭 -->
<character>
<literal>旭</literal>

<stroke_count>6</stroke_count>
<freq>1417</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">キョク</reading>
<reading r_type="ja_kun">あさひ</reading>
<meaning>rising sun</meaning>
<meaning>morning sun</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 葦 -->
<character>
<literal>葦</literal>

<stroke_count>13</stroke_count>
<freq>2343</freq>

<reading_meaning>

<reading r_type="ja_on">イ</reading>
<reading r_type="ja_kun">あし</reading>
<reading r_type="ja_kun">よし</reading>
<reading r_type="ja_kun">しお.れる</reading>
<reading r_type="ja_kun">しな.びる</reading>
<reading r_type="ja_kun">しぼ.む</reading>
<reading r_type="ja_kun">な.える</reading>
<meaning>reed</meaning>
<meaning>bullrush</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 芦 -->
<character>
<literal>芦</literal>

<stroke_count>7</stroke_count>
<freq>1733</freq>

<reading_meaning>

<reading r_type="ja_on">ロ</reading>
<reading r_type="ja_kun">あし</reading>
<reading r_type="ja_kun">よし</reading>
<meaning>reed</meaning>
<meaning>bullrush</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 鯵 -->
<character>
<literal>鯵</literal>

<stroke_count>19</stroke_count>

<reading_meaning>

<reading r_type="ja_on">ソウ</reading>
<reading r_type="ja_kun">あじ</reading>
<meaning>horse mackerel</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 梓 -->
<character>
<literal>梓</literal>

<stroke_count>11</stroke_count>
<freq>2301</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">シ</reading>
<reading r_type="ja_kun">あずさ</reading>
<meaning>catalpa tree</meaning>
<meaning>woodblock printing</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 圧 -->
<character>
<literal>圧</literal>

<stroke_count>5</stroke_count>
<freq>718</freq>
<jlpt>2</jlpt>

<reading_meaning>

<reading r_type="ja_on">アツ</reading>
<reading r_type="ja_on">エン</reading>
<reading r_type="ja_on">オウ</reading>
<reading r_type="ja_kun">お.す</reading>
<reading r_type="ja_kun">へ.す</reading>
<reading r_type="ja_kun">おさ.える</reading>
<reading r_type="ja_kun">お.さえる</reading>
<meaning>pressure</meaning>
<meaning>push</meaning>
<meaning>overwhelm</meaning>
<meaning>oppress</meaning>
<meaning>dominate</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 斡 -->
<character>
<literal>斡</literal>

<stroke_count>14</stroke_count>

<reading_meaning>

<reading r_type="ja_on">アツ</reading>
<reading r_type="ja_on">カン</reading>
<reading r_type="ja_on">ワツ</reading>
<reading r_type="ja_kun">めぐ.る</reading>
<reading r_type="ja_kun">めぐ.らす</reading>
<meaning>go around</meaning>
<meaning>rule</meaning>
<meaning>administer</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 扱 -->
<character>
<literal>扱</literal>

<stroke_count>6</stroke_count>
<freq>1057</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">ソウ</reading>
<reading r_type="ja_on">キュウ</reading>
<reading r_type="ja_kun">あつか.い</reading>
<reading r_type="ja_kun">あつか.う</reading>
<reading r_type="ja_kun">あつか.る</reading>
<reading r_type="ja_kun">こ.く</reading>
<meaning>handle</meaning>
<meaning>entertain</meaning>
<meaning>thresh</meaning>
<meaning>strip</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 宛 -->
<character>
<literal>宛</literal>

<stroke_count>8</stroke_count>

<reading_meaning>

<reading r_type="ja_on">エン</reading>
<reading r_type="ja_kun">あ.てる</reading>
<reading r_type="ja_kun">-あて</reading>
<reading r_type="ja_kun">-づつ</reading>
<reading r_type="ja_kun">あたか.も</reading>
<meaning>address</meaning>
<meaning>just like</meaning>
<meaning>fortunately</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 姐 -->
<character>
<literal>姐</literal>

<stroke_count>8</stroke_count>

<reading_meaning>

<reading r_type="ja_on">ソ</reading>
<reading r_type="ja_on">シャ</reading>
<reading r_type="ja_kun">あね</reading>
<reading r_type="ja_kun">ねえさん</reading>
<meaning>elder sister</meaning>
<meaning>maidservant</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 虻 -->
<character>
<literal>虻</literal>

<stroke_count>9</stroke_count>

<reading_meaning>

<reading r_type="ja_on">ボウ</reading>
<reading r_type="ja_kun">あぶ</reading>
<meaning>gadfly</meaning>
<meaning>horsefly</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 飴 -->
<character>
<literal>飴</literal>

<stroke_count>13</stroke_count>
<stroke_count>14</stroke_count>

<reading_meaning>

<reading r_type="ja_on">イ</reading>
<reading r_type="ja_on">シ</reading>
<reading r_type="ja_kun">あめ</reading>
<reading r_type="ja_kun">やしな.う</reading>
<meaning>rice jelly</meaning>
<meaning>candy</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 絢 -->
<character>
<literal>絢</literal>

<stroke_count>12</stroke_count>
<freq>2315</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">ケン</reading>
<meaning>brilliant fabric design</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 綾 -->
<character>
<literal>綾</literal>

<stroke_count>14</stroke_count>
<freq>1759</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">リン</reading>
<reading r_type="ja_kun">あや</reading>
<meaning>design</meaning>
<meaning>figured cloth</meaning>
<meaning>twill</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 鮎 -->
<character>
<literal>鮎</literal>

<stroke_count>16</stroke_count>
<freq>2201</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">デン</reading>
<reading r_type="ja_on">ネン</reading>
<reading r_type="ja_kun">あゆ</reading>
<reading r_type="ja_kun">なまず</reading>
<meaning>freshwater trout</meaning>
<meaning>smelt</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 或 -->
<character>
<literal>或</literal>

<stroke_count>8</stroke_count>
<freq>2378</freq>

<reading_meaning>

<reading r_type="ja_on">ワク</reading>
<reading r_type="ja_on">コク</reading>
<reading r_type="ja_on">イキ</reading>
<reading r_type="ja_kun">あ.る</reading>
<reading r_type="ja_kun">あるい</reading>
<reading r_type="ja_kun">あるいは</reading>
<meaning>some</meaning>
<meaning>one</meaning>
<meaning>or</meaning>
<meaning>possibly</meaning>
<meaning>a certain</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 粟 -->
<character>
<literal>粟</literal>

<stroke_count>12</stroke_count>
<freq>2146</freq>

<reading_meaning>

<reading r_type="ja_on">ゾク</reading>
<reading r_type="ja_on">ショク</reading>
<reading r_type="ja_on">ソク</reading>
<reading r_type="ja_kun">あわ</reading>
<reading r_type="ja_kun">もみ</reading>
<meaning>millet</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 袷 -->
<character>
<literal>袷</literal>

<stroke_count>11</stroke_count>

<reading_meaning>

<reading r_type="ja_on">コウ</reading>
<reading r_type="ja_on">キョウ</reading>
<reading r_type="ja_kun">あわせ</reading>
<meaning>lined (kimono)</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 安 -->
<character>
<literal>安</literal>

<stroke_count>6</stroke_count>
<freq>144</freq>
<jlpt>4</jlpt>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_kun">やす.い</reading>
<reading r_type="ja_kun">やす.まる</reading>
<reading r_type="ja_kun">やす</reading>
<reading r_type="ja_kun">やす.らか</reading>
<meaning>relax</meaning>
<meaning>cheap</meaning>
<meaning>low</meaning>
<meaning>quiet</meaning>
<meaning>rested</meaning>
<meaning>contented</meaning>
<meaning>peaceful</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 庵 -->
<character>
<literal>庵</literal>

<stroke_count>11</stroke_count>
<freq>2119</freq>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_kun">いおり</reading>
<reading r_type="ja_kun">いお</reading>
<meaning>hermitage</meaning>
<meaning>retreat</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 按 -->
<character>
<literal>按</literal>

<stroke_count>9</stroke_count>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_kun">おさ.える</reading>
<reading r_type="ja_kun">しら.べる</reading>
<meaning>hold</meaning>
<meaning>consider</meaning>
<meaning>investigate</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 暗 -->
<character>
<literal>暗</literal>

<stroke_count>13</stroke_count>
<freq>1040</freq>
<jlpt>3</jlpt>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_kun">くら.い</reading>
<reading r_type="ja_kun">くら.む</reading>
<reading r_type="ja_kun">くれ.る</reading>
<meaning>darkness</meaning>
<meaning>disappear</meaning>
<meaning>shade</meaning>
<meaning>informal</meaning>
<meaning>grow dark</meaning>
<meaning>be blinded</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 案 -->
<character>
<literal>案</literal>

<stroke_count>10</stroke_count>
<freq>206</freq>
<jlpt>2</jlpt>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_kun">つくえ</reading>
<meaning>plan</meaning>
<meaning>suggestion</meaning>
<meaning>draft</meaning>
<meaning>ponder</meaning>
<meaning>fear</meaning>
<meaning>proposition</meaning>
<meaning>idea</meaning>
<meaning>expectation</meaning>
<meaning>worry</meaning>
<meaning>table</meaning>
<meaning>bench</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 闇 -->
<character>
<literal>闇</literal>

<stroke_count>17</stroke_count>
<freq>1969</freq>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_on">オン</reading>
<reading r_type="ja_kun">やみ</reading>
<reading r_type="ja_kun">くら.い</reading>
<meaning>get dark</meaning>
<meaning>gloom</meaning>
<meaning>disorder</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 鞍 -->
<character>
<literal>鞍</literal>

<stroke_count>15</stroke_count>
<freq>2214</freq>

<reading_meaning>

<reading r_type="ja_on">アン</reading>
<reading r_type="ja_kun">くら</reading>
<meaning>saddle</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 杏 -->
<character>
<literal>杏</literal>

<stroke_count>7</stroke_count>
<freq>2159</freq>
<jlpt>1</jlpt>

<reading_meaning>

<reading r_type="ja_on">キョウ</reading>
<reading r_type="ja_on">アン</reading>
<reading r_type="ja_on">コウ</reading>
<reading r_type="ja_kun">あんず</reading>
<meaning>apricot</meaning>

</reading_meaning>
</character>
<!-- Entry for Kanji: 以 -->
<character>
<literal>以</literal>

<stroke_count>5</stroke_count>
<freq>126</freq>
<jlpt>3</jlpt>

<reading_meaning>

<reading r_type="ja_on">イ</reading>